language: node_js
node_js:
  - 0.12

before_script:
  - "npm install -g gulp-cli"
  - "npm install -g karma"
  - "npm install"

script:
  - "./node_modules/.bin/karma start karma.conf.js --browsers PhantomJS --single-run"
